### PR TITLE
Fix assert exception when template body is empty string

### PR DESCRIPTION
**Pull request by xxyzz**
- I have run the mypy command on the dumpparser.py file and mypy didn't find any issue.
- I removed the typestubs folder and disabled type checking for the Lupa package.  IMO We should focus on adding more typing to our code first... That's just my 2 cents.
- I could add a GitHub Actions job to run [mypy](https://github.com/python/mypy), [black](https://github.com/psf/black) and [ruff](https://github.com/astral-sh/ruff). But this also need to change lots of code.

### CODE REVIEW

**Comment by kristian-clausal** [comment]
I am already in the middle of writing a Lupa typestub.

**Comment by xxyzz** [comment]
But why...

**Comment by xxyzz** [comment]
Could you please reopen this pull request? I have reverted my last commit.

**Comment by kristian-clausal** [comment]
I am just creating a very basic lupa stub .pyi file for use with our project.

Changing the branch disables reopening the pull request (see [https://gist.github.com/Farhan-Haseeb/fd4cbb476de4e2931c322d7bacb75e5f]) so you might need to recreate the pull request.

**Pull request closed without merging**
