### PR TITLE
Update template matching regex in `Wtp._encode()`

### LINKED ISSUE #72: Paser can't parse templates that have `{}` in arguemnt
Similar to #59, example page: https://zh.wiktionary.org/wiki/%, wikitext:

```
#: {{zh-x|約 有 6 '''%'''{pā} 的 臺灣人 血型 是 A{ēi}B{bī}型。|}}
```

The text inside curly brackets is Pinyin for the previous character, this data is ignored by MediWiki and not displayed in the expanded HTML. I haven't find the Wikitext document for this syntax, maybe it's already obsolete. This time a temporary fix with magic character would be hard to implement.

### PR DESCRIPTION
**Pull request by xxyzz**
Fixes #72 and #59

### CODE REVIEW

**Comment by kristian-clausal** [comment]
I wish I knew what was happening in that regex. LGTM!

**Comment by xxyzz** [comment]
I use this [website](https://regex101.com/r/BMxRFB/1) to see which part of the text is matched but I still don't know what kind of text the first two alternatives regex patterns(`{\|[^{}]*?\|}` and `}[^{}]`) are trying to match.

**Comment by kristian-clausal** [comment]
The first pattern is the outermost brackets of a table, but the second one is still weird to me. I'm going through the section with this, and it could really need with some documentation and maybe some named consts.

**Comment by xxyzz** [comment]
A table as a template argument? Could you find an example?

The second alternative pattern was added in https://github.com/tatuylonen/wikitextprocessor/commit/ee043cff190543fb94cb40d4827444d8982a30fe, looks like the second pattern was added by mistake.

**Comment by kristian-clausal** [comment]
Wikitext documentation seems to indicate you should be able to add them. It's hard to test this because I need to find a template that just... prints out stuff.

Trying with #if, I can't get it to accept {|.
```
{{#if: true|
{{{!}}
{{!}}-
! tesssst !! tesst !! tesssssssst
{{!}}-
{{!}}test {{!}}{{!}} test2 {{!}}{{!}} test3
{{!}}}
|}}
```
Have to escape the vbars with `{{!}}`.

**Comment by xxyzz** [comment]
This first `{\|[^{}]*?\|}` pattern was added from this commit: https://github.com/tatuylonen/wikitextprocessor/commit/1e7539728e25e4f35c20467d36916b6b5fc3771a#diff-9d58f4d4915c12ad491e1b91e228f1033209f5a4b0078dd6d68f7f39dd0d2a87R345

The commit message says the change was for parsing incorrect Wikitext.

**Pull request merged**
